services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aws_rag_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: aws_rag
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
